// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identidad.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarUsuario = `-- name: ActualizarUsuario :one
UPDATE usuarios
SET
    contrasena_hash = $2,
    estado = $3,
    tiene_mfa = $4,
    actualizado_en = $5
WHERE id = $1
RETURNING id, correo, contrasena_hash, estado, tiene_mfa, creado_en, actualizado_en, ultimo_acceso_en
`

type ActualizarUsuarioParams struct {
	ID             pgtype.UUID        `json:"id"`
	ContrasenaHash string             `json:"contrasena_hash"`
	Estado         string             `json:"estado"`
	TieneMfa       bool               `json:"tiene_mfa"`
	ActualizadoEn  pgtype.Timestamptz `json:"actualizado_en"`
}

// Persiste el estado completo del agregado tras una mutación de negocio
// (cambio de contraseña, transición de estado, flip de tiene_mfa,
// actualizado_en). ultimo_acceso_en se actualiza aparte con
// RegistrarAccesoUsuario, ya que RegistrarAcceso no siempre corre en la
// misma llamada que las demás mutaciones.
func (q *Queries) ActualizarUsuario(ctx context.Context, arg ActualizarUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, actualizarUsuario,
		arg.ID,
		arg.ContrasenaHash,
		arg.Estado,
		arg.TieneMfa,
		arg.ActualizadoEn,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Correo,
		&i.ContrasenaHash,
		&i.Estado,
		&i.TieneMfa,
		&i.CreadoEn,
		&i.ActualizadoEn,
		&i.UltimoAccesoEn,
	)
	return i, err
}

const crearUsuario = `-- name: CrearUsuario :one

INSERT INTO usuarios (
    id,
    correo,
    contrasena_hash,
    estado,
    tiene_mfa,
    creado_en,
    actualizado_en
) VALUES (
    $1, $2, $3, $4, $5, $6, $6
)
RETURNING id, correo, contrasena_hash, estado, tiene_mfa, creado_en, actualizado_en, ultimo_acceso_en
`

type CrearUsuarioParams struct {
	ID             pgtype.UUID        `json:"id"`
	Correo         string             `json:"correo"`
	ContrasenaHash string             `json:"contrasena_hash"`
	Estado         string             `json:"estado"`
	TieneMfa       bool               `json:"tiene_mfa"`
	CreadoEn       pgtype.Timestamptz `json:"creado_en"`
}

// Queries sqlc del contexto Identidad. Implementan
// identidad/puertos.RepositorioUsuarios (ver
// docs/design/identidad-bounded-context.md, sección 2.2).
//
// Regla de frontera (INV-ID-20): solo el adaptador
// identidad/adaptadores/postgres consume este código generado. Ningún otro
// contexto importa internal/identidad/adaptadores/postgres/sqlc.
func (q *Queries) CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, crearUsuario,
		arg.ID,
		arg.Correo,
		arg.ContrasenaHash,
		arg.Estado,
		arg.TieneMfa,
		arg.CreadoEn,
	)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Correo,
		&i.ContrasenaHash,
		&i.Estado,
		&i.TieneMfa,
		&i.CreadoEn,
		&i.ActualizadoEn,
		&i.UltimoAccesoEn,
	)
	return i, err
}

const eliminarTokenVerificacionCorreoPorUsuario = `-- name: EliminarTokenVerificacionCorreoPorUsuario :exec
DELETE FROM tokens_verificacion_correo
WHERE usuario_id = $1
`

func (q *Queries) EliminarTokenVerificacionCorreoPorUsuario(ctx context.Context, usuarioID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, eliminarTokenVerificacionCorreoPorUsuario, usuarioID)
	return err
}

const obtenerTokenVerificacionCorreoPorHash = `-- name: ObtenerTokenVerificacionCorreoPorHash :one
SELECT hash_token, usuario_id, expira_en, creado_en
FROM tokens_verificacion_correo
WHERE hash_token = $1
`

func (q *Queries) ObtenerTokenVerificacionCorreoPorHash(ctx context.Context, hashToken string) (TokensVerificacionCorreo, error) {
	row := q.db.QueryRow(ctx, obtenerTokenVerificacionCorreoPorHash, hashToken)
	var i TokensVerificacionCorreo
	err := row.Scan(
		&i.HashToken,
		&i.UsuarioID,
		&i.ExpiraEn,
		&i.CreadoEn,
	)
	return i, err
}

const obtenerUsuarioPorCorreo = `-- name: ObtenerUsuarioPorCorreo :one
SELECT id, correo, contrasena_hash, estado, tiene_mfa, creado_en, actualizado_en, ultimo_acceso_en
FROM usuarios
WHERE correo = $1
`

func (q *Queries) ObtenerUsuarioPorCorreo(ctx context.Context, correo string) (Usuario, error) {
	row := q.db.QueryRow(ctx, obtenerUsuarioPorCorreo, correo)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Correo,
		&i.ContrasenaHash,
		&i.Estado,
		&i.TieneMfa,
		&i.CreadoEn,
		&i.ActualizadoEn,
		&i.UltimoAccesoEn,
	)
	return i, err
}

const obtenerUsuarioPorID = `-- name: ObtenerUsuarioPorID :one
SELECT id, correo, contrasena_hash, estado, tiene_mfa, creado_en, actualizado_en, ultimo_acceso_en
FROM usuarios
WHERE id = $1
`

func (q *Queries) ObtenerUsuarioPorID(ctx context.Context, id pgtype.UUID) (Usuario, error) {
	row := q.db.QueryRow(ctx, obtenerUsuarioPorID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Correo,
		&i.ContrasenaHash,
		&i.Estado,
		&i.TieneMfa,
		&i.CreadoEn,
		&i.ActualizadoEn,
		&i.UltimoAccesoEn,
	)
	return i, err
}

const registrarAccesoUsuario = `-- name: RegistrarAccesoUsuario :one
UPDATE usuarios
SET
    ultimo_acceso_en = $2,
    actualizado_en = $2
WHERE id = $1
RETURNING id, correo, contrasena_hash, estado, tiene_mfa, creado_en, actualizado_en, ultimo_acceso_en
`

type RegistrarAccesoUsuarioParams struct {
	ID             pgtype.UUID        `json:"id"`
	UltimoAccesoEn pgtype.Timestamptz `json:"ultimo_acceso_en"`
}

// Usuario.RegistrarAcceso(ahora): marca el último inicio de sesión exitoso.
func (q *Queries) RegistrarAccesoUsuario(ctx context.Context, arg RegistrarAccesoUsuarioParams) (Usuario, error) {
	row := q.db.QueryRow(ctx, registrarAccesoUsuario, arg.ID, arg.UltimoAccesoEn)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Correo,
		&i.ContrasenaHash,
		&i.Estado,
		&i.TieneMfa,
		&i.CreadoEn,
		&i.ActualizadoEn,
		&i.UltimoAccesoEn,
	)
	return i, err
}

const upsertTokenVerificacionCorreo = `-- name: UpsertTokenVerificacionCorreo :exec

INSERT INTO tokens_verificacion_correo (
    hash_token, usuario_id, expira_en
) VALUES (
    $1, $2, $3
)
ON CONFLICT (usuario_id) DO UPDATE
SET hash_token = EXCLUDED.hash_token,
    expira_en = EXCLUDED.expira_en
`

type UpsertTokenVerificacionCorreoParams struct {
	HashToken string             `json:"hash_token"`
	UsuarioID pgtype.UUID        `json:"usuario_id"`
	ExpiraEn  pgtype.Timestamptz `json:"expira_en"`
}

// Queries de tokens_verificacion_correo. Implementan
// identidad/puertos.RepositorioTokensVerificacion (sección 3.4 del diseño).
// usuario_id es UNIQUE (000004): un reenvío invalida el token anterior sin
// un paso de borrado previo (RepositorioTokensVerificacion.Guardar debe ser
// un upsert real, no dos queries separados).
func (q *Queries) UpsertTokenVerificacionCorreo(ctx context.Context, arg UpsertTokenVerificacionCorreoParams) error {
	_, err := q.db.Exec(ctx, upsertTokenVerificacionCorreo, arg.HashToken, arg.UsuarioID, arg.ExpiraEn)
	return err
}
