// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Persiste el estado completo del agregado tras una mutación de negocio
	// (cambio de contraseña, transición de estado, flip de tiene_mfa,
	// actualizado_en). ultimo_acceso_en se actualiza aparte con
	// RegistrarAccesoUsuario, ya que RegistrarAcceso no siempre corre en la
	// misma llamada que las demás mutaciones.
	ActualizarUsuario(ctx context.Context, arg ActualizarUsuarioParams) (Usuario, error)
	// Queries sqlc del contexto Identidad. Implementan
	// identidad/puertos.RepositorioUsuarios (ver
	// docs/design/identidad-bounded-context.md, sección 2.2).
	//
	// Regla de frontera (INV-ID-20): solo el adaptador
	// identidad/adaptadores/postgres consume este código generado. Ningún otro
	// contexto importa internal/identidad/adaptadores/postgres/sqlc.
	CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (Usuario, error)
	EliminarTokenVerificacionCorreoPorUsuario(ctx context.Context, usuarioID pgtype.UUID) error
	ObtenerTokenVerificacionCorreoPorHash(ctx context.Context, hashToken string) (TokensVerificacionCorreo, error)
	ObtenerUsuarioPorCorreo(ctx context.Context, correo string) (Usuario, error)
	ObtenerUsuarioPorID(ctx context.Context, id pgtype.UUID) (Usuario, error)
	// Usuario.RegistrarAcceso(ahora): marca el último inicio de sesión exitoso.
	RegistrarAccesoUsuario(ctx context.Context, arg RegistrarAccesoUsuarioParams) (Usuario, error)
	// Queries de tokens_verificacion_correo. Implementan
	// identidad/puertos.RepositorioTokensVerificacion (sección 3.4 del diseño).
	// usuario_id es UNIQUE (000004): un reenvío invalida el token anterior sin
	// un paso de borrado previo (RepositorioTokensVerificacion.Guardar debe ser
	// un upsert real, no dos queries separados).
	UpsertTokenVerificacionCorreo(ctx context.Context, arg UpsertTokenVerificacionCorreoParams) error
}

var _ Querier = (*Queries)(nil)
