// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: acceso.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarSesion = `-- name: ActualizarSesion :one
UPDATE sesiones
SET estado = $2,
    generacion = $3,
    actualizada_en = $4,
    ultima_renovacion_en = $5,
    expira_inactividad_en = $6,
    revocada_en = $7,
    motivo_revocacion = $8
WHERE id = $1
RETURNING id, usuario_id, estado, generacion, creada_en, actualizada_en, ultima_renovacion_en, expira_inactividad_en, expira_absoluto_en, revocada_en, motivo_revocacion, ip_origen, agente_usuario, huella_dispositivo
`

type ActualizarSesionParams struct {
	ID                  pgtype.UUID        `json:"id"`
	Estado              string             `json:"estado"`
	Generacion          int32              `json:"generacion"`
	ActualizadaEn       pgtype.Timestamptz `json:"actualizada_en"`
	UltimaRenovacionEn  pgtype.Timestamptz `json:"ultima_renovacion_en"`
	ExpiraInactividadEn pgtype.Timestamptz `json:"expira_inactividad_en"`
	RevocadaEn          pgtype.Timestamptz `json:"revocada_en"`
	MotivoRevocacion    pgtype.Text        `json:"motivo_revocacion"`
}

// Persiste el estado completo del agregado tras una mutación de negocio
// (Rotar, Revocar, MarcarExpirada). No hay un flag "es nuevo" en el
// dominio (INV-ACC-09: sin campos exportados), así que el adaptador
// intenta primero este UPDATE; si no afecta ninguna fila (pgx.ErrNoRows en
// un :one con RETURNING) es porque la sesión todavía no existe y entonces
// se hace el INSERT (CrearSesion) — mismo patrón que
// identidad/adaptadores/postgres.RepositorioUsuarios.Guardar.
func (q *Queries) ActualizarSesion(ctx context.Context, arg ActualizarSesionParams) (Sesione, error) {
	row := q.db.QueryRow(ctx, actualizarSesion,
		arg.ID,
		arg.Estado,
		arg.Generacion,
		arg.ActualizadaEn,
		arg.UltimaRenovacionEn,
		arg.ExpiraInactividadEn,
		arg.RevocadaEn,
		arg.MotivoRevocacion,
	)
	var i Sesione
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Estado,
		&i.Generacion,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.UltimaRenovacionEn,
		&i.ExpiraInactividadEn,
		&i.ExpiraAbsolutoEn,
		&i.RevocadaEn,
		&i.MotivoRevocacion,
		&i.IpOrigen,
		&i.AgenteUsuario,
		&i.HuellaDispositivo,
	)
	return i, err
}

const consumirTokenRefresco = `-- name: ConsumirTokenRefresco :exec
UPDATE tokens_refresco
SET consumido_en = $2, hash_sucesor = $3
WHERE hash_token = $1
`

type ConsumirTokenRefrescoParams struct {
	HashToken   string             `json:"hash_token"`
	ConsumidoEn pgtype.Timestamptz `json:"consumido_en"`
	HashSucesor pgtype.Text        `json:"hash_sucesor"`
}

// Marca el token recién rotado (Sesion.RefrescoRecienConsumido) como
// consumido, con su sucesor. Debe ejecutarse ANTES de CrearTokenRefresco en
// la misma rotación: hasta que este UPDATE quita al token anterior de la
// vigencia (consumido_en pasa de NULL a NOT NULL), el índice único parcial
// seguiría contándolo como "vigente" y el INSERT del nuevo token violaría
// la unicidad incluso sin ninguna concurrencia real.
func (q *Queries) ConsumirTokenRefresco(ctx context.Context, arg ConsumirTokenRefrescoParams) error {
	_, err := q.db.Exec(ctx, consumirTokenRefresco, arg.HashToken, arg.ConsumidoEn, arg.HashSucesor)
	return err
}

const contarSesionesActivasDeUsuario = `-- name: ContarSesionesActivasDeUsuario :one
SELECT COUNT(*) FROM sesiones WHERE usuario_id = $1 AND estado = 'activa'
`

func (q *Queries) ContarSesionesActivasDeUsuario(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarSesionesActivasDeUsuario, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearSesion = `-- name: CrearSesion :one

INSERT INTO sesiones (
    id, usuario_id, estado, generacion, creada_en, actualizada_en,
    expira_inactividad_en, expira_absoluto_en,
    ip_origen, agente_usuario, huella_dispositivo
) VALUES (
    $1, $2, $3, $4, $5, $5, $6, $7, $8, $9, $10
)
RETURNING id, usuario_id, estado, generacion, creada_en, actualizada_en, ultima_renovacion_en, expira_inactividad_en, expira_absoluto_en, revocada_en, motivo_revocacion, ip_origen, agente_usuario, huella_dispositivo
`

type CrearSesionParams struct {
	ID                  pgtype.UUID        `json:"id"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Estado              string             `json:"estado"`
	Generacion          int32              `json:"generacion"`
	CreadaEn            pgtype.Timestamptz `json:"creada_en"`
	ExpiraInactividadEn pgtype.Timestamptz `json:"expira_inactividad_en"`
	ExpiraAbsolutoEn    pgtype.Timestamptz `json:"expira_absoluto_en"`
	IpOrigen            *netip.Addr        `json:"ip_origen"`
	AgenteUsuario       pgtype.Text        `json:"agente_usuario"`
	HuellaDispositivo   pgtype.Text        `json:"huella_dispositivo"`
}

// Queries sqlc del contexto Acceso. Implementan
// acceso/puertos.RepositorioSesiones (ver
// docs/design/acceso-bounded-context.md, sección 2.2, y la migración
// 000006_crear_sesiones.up.sql).
//
// Regla de frontera (INV-ACC-20, mismo criterio que INV-ID-20 de
// Identidad): solo el adaptador acceso/adaptadores/postgres consume este
// código generado. Ningún otro contexto importa
// internal/acceso/adaptadores/postgres/sqlc.
//
// Nota sobre RevocarSesionesActivasDeUsuario: el parámetro "excepto" NO se
// vuelve NULL cuando el caso de uso no quiere preservar ninguna sesión
// (dominio.IDSesion{} vacío) — el adaptador (mapeo.go) lo traduce al UUID
// nulo "00000000-0000-0000-0000-000000000000", que dominio.IDSesionDesde ya
// rechaza como identificador válido (esUUIDNulo), así que nunca puede
// coincidir con el id real de una sesión (los IDSesion son UUIDv7). Evita
// tener que manejar NULL en el predicado SQL para el caso común.
func (q *Queries) CrearSesion(ctx context.Context, arg CrearSesionParams) (Sesione, error) {
	row := q.db.QueryRow(ctx, crearSesion,
		arg.ID,
		arg.UsuarioID,
		arg.Estado,
		arg.Generacion,
		arg.CreadaEn,
		arg.ExpiraInactividadEn,
		arg.ExpiraAbsolutoEn,
		arg.IpOrigen,
		arg.AgenteUsuario,
		arg.HuellaDispositivo,
	)
	var i Sesione
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Estado,
		&i.Generacion,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.UltimaRenovacionEn,
		&i.ExpiraInactividadEn,
		&i.ExpiraAbsolutoEn,
		&i.RevocadaEn,
		&i.MotivoRevocacion,
		&i.IpOrigen,
		&i.AgenteUsuario,
		&i.HuellaDispositivo,
	)
	return i, err
}

const crearTokenRefresco = `-- name: CrearTokenRefresco :exec
INSERT INTO tokens_refresco (hash_token, sesion_id, generacion, emitido_en, expira_en)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (hash_token) DO NOTHING
`

type CrearTokenRefrescoParams struct {
	HashToken  string             `json:"hash_token"`
	SesionID   pgtype.UUID        `json:"sesion_id"`
	Generacion int32              `json:"generacion"`
	EmitidoEn  pgtype.Timestamptz `json:"emitido_en"`
	ExpiraEn   pgtype.Timestamptz `json:"expira_en"`
}

// ON CONFLICT DO NOTHING: RepositorioSesiones.Guardar debe ser idempotente
// respecto a los tokens ya persistidos y sin cambios (§2.2 del diseño). El
// índice único parcial tokens_refresco_vigente_por_sesion_idx (migración
// 000006) es quien realmente hace cumplir INV-ACC-04 bajo concurrencia: una
// violación de ESE índice (no de esta clave primaria) es la que el
// adaptador traduce a dominio.ErrConcurrenciaSesion.
func (q *Queries) CrearTokenRefresco(ctx context.Context, arg CrearTokenRefrescoParams) error {
	_, err := q.db.Exec(ctx, crearTokenRefresco,
		arg.HashToken,
		arg.SesionID,
		arg.Generacion,
		arg.EmitidoEn,
		arg.ExpiraEn,
	)
	return err
}

const listarSesionesActivasDeUsuario = `-- name: ListarSesionesActivasDeUsuario :many
SELECT id, usuario_id, estado, generacion, creada_en, actualizada_en, ultima_renovacion_en, expira_inactividad_en, expira_absoluto_en, revocada_en, motivo_revocacion, ip_origen, agente_usuario, huella_dispositivo FROM sesiones WHERE usuario_id = $1 AND estado = 'activa' ORDER BY creada_en DESC
`

func (q *Queries) ListarSesionesActivasDeUsuario(ctx context.Context, usuarioID pgtype.UUID) ([]Sesione, error) {
	rows, err := q.db.Query(ctx, listarSesionesActivasDeUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sesione
	for rows.Next() {
		var i Sesione
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Estado,
			&i.Generacion,
			&i.CreadaEn,
			&i.ActualizadaEn,
			&i.UltimaRenovacionEn,
			&i.ExpiraInactividadEn,
			&i.ExpiraAbsolutoEn,
			&i.RevocadaEn,
			&i.MotivoRevocacion,
			&i.IpOrigen,
			&i.AgenteUsuario,
			&i.HuellaDispositivo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerSesionPorID = `-- name: ObtenerSesionPorID :one
SELECT id, usuario_id, estado, generacion, creada_en, actualizada_en, ultima_renovacion_en, expira_inactividad_en, expira_absoluto_en, revocada_en, motivo_revocacion, ip_origen, agente_usuario, huella_dispositivo FROM sesiones WHERE id = $1
`

func (q *Queries) ObtenerSesionPorID(ctx context.Context, id pgtype.UUID) (Sesione, error) {
	row := q.db.QueryRow(ctx, obtenerSesionPorID, id)
	var i Sesione
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Estado,
		&i.Generacion,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.UltimaRenovacionEn,
		&i.ExpiraInactividadEn,
		&i.ExpiraAbsolutoEn,
		&i.RevocadaEn,
		&i.MotivoRevocacion,
		&i.IpOrigen,
		&i.AgenteUsuario,
		&i.HuellaDispositivo,
	)
	return i, err
}

const obtenerTokenRefrescoPorHash = `-- name: ObtenerTokenRefrescoPorHash :one
SELECT hash_token, sesion_id, generacion, emitido_en, expira_en, consumido_en, hash_sucesor FROM tokens_refresco WHERE hash_token = $1
`

func (q *Queries) ObtenerTokenRefrescoPorHash(ctx context.Context, hashToken string) (TokensRefresco, error) {
	row := q.db.QueryRow(ctx, obtenerTokenRefrescoPorHash, hashToken)
	var i TokensRefresco
	err := row.Scan(
		&i.HashToken,
		&i.SesionID,
		&i.Generacion,
		&i.EmitidoEn,
		&i.ExpiraEn,
		&i.ConsumidoEn,
		&i.HashSucesor,
	)
	return i, err
}

const revocarSesionesActivasDeUsuario = `-- name: RevocarSesionesActivasDeUsuario :many
UPDATE sesiones
SET estado = 'revocada',
    revocada_en = $2,
    motivo_revocacion = $3,
    actualizada_en = $2
WHERE usuario_id = $1 AND estado = 'activa' AND id <> $4
RETURNING id
`

type RevocarSesionesActivasDeUsuarioParams struct {
	UsuarioID        pgtype.UUID        `json:"usuario_id"`
	RevocadaEn       pgtype.Timestamptz `json:"revocada_en"`
	MotivoRevocacion pgtype.Text        `json:"motivo_revocacion"`
	ID               pgtype.UUID        `json:"id"`
}

// Operación de conjunto (RepositorioSesiones.RevocarActivasDeUsuario, §2.2
// del diseño): revocar N sesiones cargando N agregados sería absurdo.
// Devuelve los ids revocados para que el caso de uso audite una fila por
// sesión y los propague a la lista de revocación de Redis.
func (q *Queries) RevocarSesionesActivasDeUsuario(ctx context.Context, arg RevocarSesionesActivasDeUsuarioParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, revocarSesionesActivasDeUsuario,
		arg.UsuarioID,
		arg.RevocadaEn,
		arg.MotivoRevocacion,
		arg.ID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
