// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Persiste el estado completo del agregado tras una mutación de negocio
	// (Rotar, Revocar, MarcarExpirada). No hay un flag "es nuevo" en el
	// dominio (INV-ACC-09: sin campos exportados), así que el adaptador
	// intenta primero este UPDATE; si no afecta ninguna fila (pgx.ErrNoRows en
	// un :one con RETURNING) es porque la sesión todavía no existe y entonces
	// se hace el INSERT (CrearSesion) — mismo patrón que
	// identidad/adaptadores/postgres.RepositorioUsuarios.Guardar.
	ActualizarSesion(ctx context.Context, arg ActualizarSesionParams) (Sesione, error)
	// Marca el token recién rotado (Sesion.RefrescoRecienConsumido) como
	// consumido, con su sucesor. Debe ejecutarse ANTES de CrearTokenRefresco en
	// la misma rotación: hasta que este UPDATE quita al token anterior de la
	// vigencia (consumido_en pasa de NULL a NOT NULL), el índice único parcial
	// seguiría contándolo como "vigente" y el INSERT del nuevo token violaría
	// la unicidad incluso sin ninguna concurrencia real.
	ConsumirTokenRefresco(ctx context.Context, arg ConsumirTokenRefrescoParams) error
	ContarSesionesActivasDeUsuario(ctx context.Context, usuarioID pgtype.UUID) (int64, error)
	// Queries sqlc del contexto Acceso. Implementan
	// acceso/puertos.RepositorioSesiones (ver
	// docs/design/acceso-bounded-context.md, sección 2.2, y la migración
	// 000006_crear_sesiones.up.sql).
	//
	// Regla de frontera (INV-ACC-20, mismo criterio que INV-ID-20 de
	// Identidad): solo el adaptador acceso/adaptadores/postgres consume este
	// código generado. Ningún otro contexto importa
	// internal/acceso/adaptadores/postgres/sqlc.
	//
	// Nota sobre RevocarSesionesActivasDeUsuario: el parámetro "excepto" NO se
	// vuelve NULL cuando el caso de uso no quiere preservar ninguna sesión
	// (dominio.IDSesion{} vacío) — el adaptador (mapeo.go) lo traduce al UUID
	// nulo "00000000-0000-0000-0000-000000000000", que dominio.IDSesionDesde ya
	// rechaza como identificador válido (esUUIDNulo), así que nunca puede
	// coincidir con el id real de una sesión (los IDSesion son UUIDv7). Evita
	// tener que manejar NULL en el predicado SQL para el caso común.
	CrearSesion(ctx context.Context, arg CrearSesionParams) (Sesione, error)
	// ON CONFLICT DO NOTHING: RepositorioSesiones.Guardar debe ser idempotente
	// respecto a los tokens ya persistidos y sin cambios (§2.2 del diseño). El
	// índice único parcial tokens_refresco_vigente_por_sesion_idx (migración
	// 000006) es quien realmente hace cumplir INV-ACC-04 bajo concurrencia: una
	// violación de ESE índice (no de esta clave primaria) es la que el
	// adaptador traduce a dominio.ErrConcurrenciaSesion.
	CrearTokenRefresco(ctx context.Context, arg CrearTokenRefrescoParams) error
	ListarSesionesActivasDeUsuario(ctx context.Context, usuarioID pgtype.UUID) ([]Sesione, error)
	ObtenerSesionPorID(ctx context.Context, id pgtype.UUID) (Sesione, error)
	ObtenerTokenRefrescoPorHash(ctx context.Context, hashToken string) (TokensRefresco, error)
	// Operación de conjunto (RepositorioSesiones.RevocarActivasDeUsuario, §2.2
	// del diseño): revocar N sesiones cargando N agregados sería absurdo.
	// Devuelve los ids revocados para que el caso de uso audite una fila por
	// sesión y los propague a la lista de revocación de Redis.
	RevocarSesionesActivasDeUsuario(ctx context.Context, arg RevocarSesionesActivasDeUsuarioParams) ([]pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
