// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: confianza.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const guardarSalaDeEspera = `-- name: GuardarSalaDeEspera :exec

INSERT INTO salas_espera (
    id, alias, alcance_tipo, alcance_organizacion_id, ruta_protegida, estado,
    ritmo_admision, capacidad_maxima_cola, ventana_reclamo_ms, modo_degradado,
    cursor_base, reloj_desde, creada_por, creada_en, actualizada_en,
    abierta_en, cerrada_en
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, now(), $15, $16
)
ON CONFLICT (id) DO UPDATE SET
    alias                 = EXCLUDED.alias,
    estado                = EXCLUDED.estado,
    ritmo_admision        = EXCLUDED.ritmo_admision,
    capacidad_maxima_cola = EXCLUDED.capacidad_maxima_cola,
    ventana_reclamo_ms    = EXCLUDED.ventana_reclamo_ms,
    modo_degradado        = EXCLUDED.modo_degradado,
    cursor_base           = EXCLUDED.cursor_base,
    reloj_desde           = EXCLUDED.reloj_desde,
    actualizada_en        = now(),
    version_config        = salas_espera.version_config + 1,
    abierta_en            = EXCLUDED.abierta_en,
    cerrada_en            = EXCLUDED.cerrada_en
`

type GuardarSalaDeEsperaParams struct {
	ID                    pgtype.UUID        `json:"id"`
	Alias                 string             `json:"alias"`
	AlcanceTipo           string             `json:"alcance_tipo"`
	AlcanceOrganizacionID pgtype.UUID        `json:"alcance_organizacion_id"`
	RutaProtegida         string             `json:"ruta_protegida"`
	Estado                string             `json:"estado"`
	RitmoAdmision         int32              `json:"ritmo_admision"`
	CapacidadMaximaCola   int64              `json:"capacidad_maxima_cola"`
	VentanaReclamoMs      int32              `json:"ventana_reclamo_ms"`
	ModoDegradado         string             `json:"modo_degradado"`
	CursorBase            int64              `json:"cursor_base"`
	RelojDesde            pgtype.Timestamptz `json:"reloj_desde"`
	CreadaPor             pgtype.UUID        `json:"creada_por"`
	CreadaEn              pgtype.Timestamptz `json:"creada_en"`
	AbiertaEn             pgtype.Timestamptz `json:"abierta_en"`
	CerradaEn             pgtype.Timestamptz `json:"cerrada_en"`
}

// Queries sqlc del contexto Confianza. Implementan
// confianza/puertos.RepositorioSalasDeEspera (ver
// docs/design/colas-virtuales.md, sección 2.2/6.1, y la migración
// 000017_crear_salas_espera).
//
// Regla de frontera (INV-COLA, mismo criterio que INV-ID-20/INV-ACC-20/
// INV-TEN-29): solo el adaptador confianza/adaptadores/postgres consume
// este código generado. `creada_por` y `alcance_organizacion_id` son
// integridad referencial hacia usuarios/organizaciones, no permiso de
// lectura de esas tablas: ninguna consulta de este archivo hace JOIN contra
// `usuarios` ni `organizaciones`.
//
// No hay RLS sobre `salas_espera` (§6.1 del diseño: Confianza no es
// multi-tenant sobre esta tabla), así que estas queries no dependen de
// ningún `SET LOCAL app.*` previo, a diferencia de las de Tenencia.
// Upsert del agregado completo: los campos de identidad (alias, alcance,
// ruta, creada_por, creada_en) se fijan solo en el INSERT inicial porque
// ninguna mutación de negocio de SalaDeEspera los cambia después de
// creada la fila (dominio/sala_espera.go no expone ningún método que los
// toque); los campos operativos (estado, ritmo, capacidad, ventana,
// modo_degradado, cursor_base, reloj_desde, abierta_en, cerrada_en) se
// reescriben en cada Guardar. version_config se incrementa en cada UPDATE
// como bitácora de cuántas veces cambió la configuración operativa; el
// agregado de dominio no la lee ni la expone (no es una invariante de
// negocio, solo trazabilidad de la fila).
func (q *Queries) GuardarSalaDeEspera(ctx context.Context, arg GuardarSalaDeEsperaParams) error {
	_, err := q.db.Exec(ctx, guardarSalaDeEspera,
		arg.ID,
		arg.Alias,
		arg.AlcanceTipo,
		arg.AlcanceOrganizacionID,
		arg.RutaProtegida,
		arg.Estado,
		arg.RitmoAdmision,
		arg.CapacidadMaximaCola,
		arg.VentanaReclamoMs,
		arg.ModoDegradado,
		arg.CursorBase,
		arg.RelojDesde,
		arg.CreadaPor,
		arg.CreadaEn,
		arg.AbiertaEn,
		arg.CerradaEn,
	)
	return err
}

const listarSalasDeEsperaVigentes = `-- name: ListarSalasDeEsperaVigentes :many
SELECT id, alias, alcance_tipo, alcance_organizacion_id, ruta_protegida, estado, ritmo_admision, capacidad_maxima_cola, ventana_reclamo_ms, modo_degradado, cursor_base, reloj_desde, version_config, creada_por, creada_en, actualizada_en, abierta_en, cerrada_en FROM salas_espera
WHERE estado IN ('abierta', 'drenando')
ORDER BY creada_en
`

// Consulta del reconciliador (§3.7 del diseño), una cada 15s por réplica:
// se apoya en el índice parcial salas_espera_vigentes_idx.
func (q *Queries) ListarSalasDeEsperaVigentes(ctx context.Context) ([]SalasEspera, error) {
	rows, err := q.db.Query(ctx, listarSalasDeEsperaVigentes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalasEspera
	for rows.Next() {
		var i SalasEspera
		if err := rows.Scan(
			&i.ID,
			&i.Alias,
			&i.AlcanceTipo,
			&i.AlcanceOrganizacionID,
			&i.RutaProtegida,
			&i.Estado,
			&i.RitmoAdmision,
			&i.CapacidadMaximaCola,
			&i.VentanaReclamoMs,
			&i.ModoDegradado,
			&i.CursorBase,
			&i.RelojDesde,
			&i.VersionConfig,
			&i.CreadaPor,
			&i.CreadaEn,
			&i.ActualizadaEn,
			&i.AbiertaEn,
			&i.CerradaEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerSalaDeEsperaPorAlias = `-- name: ObtenerSalaDeEsperaPorAlias :one
SELECT id, alias, alcance_tipo, alcance_organizacion_id, ruta_protegida, estado, ritmo_admision, capacidad_maxima_cola, ventana_reclamo_ms, modo_degradado, cursor_base, reloj_desde, version_config, creada_por, creada_en, actualizada_en, abierta_en, cerrada_en FROM salas_espera WHERE alias = $1
`

func (q *Queries) ObtenerSalaDeEsperaPorAlias(ctx context.Context, alias string) (SalasEspera, error) {
	row := q.db.QueryRow(ctx, obtenerSalaDeEsperaPorAlias, alias)
	var i SalasEspera
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.AlcanceTipo,
		&i.AlcanceOrganizacionID,
		&i.RutaProtegida,
		&i.Estado,
		&i.RitmoAdmision,
		&i.CapacidadMaximaCola,
		&i.VentanaReclamoMs,
		&i.ModoDegradado,
		&i.CursorBase,
		&i.RelojDesde,
		&i.VersionConfig,
		&i.CreadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.AbiertaEn,
		&i.CerradaEn,
	)
	return i, err
}

const obtenerSalaDeEsperaPorID = `-- name: ObtenerSalaDeEsperaPorID :one
SELECT id, alias, alcance_tipo, alcance_organizacion_id, ruta_protegida, estado, ritmo_admision, capacidad_maxima_cola, ventana_reclamo_ms, modo_degradado, cursor_base, reloj_desde, version_config, creada_por, creada_en, actualizada_en, abierta_en, cerrada_en FROM salas_espera WHERE id = $1
`

func (q *Queries) ObtenerSalaDeEsperaPorID(ctx context.Context, id pgtype.UUID) (SalasEspera, error) {
	row := q.db.QueryRow(ctx, obtenerSalaDeEsperaPorID, id)
	var i SalasEspera
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.AlcanceTipo,
		&i.AlcanceOrganizacionID,
		&i.RutaProtegida,
		&i.Estado,
		&i.RitmoAdmision,
		&i.CapacidadMaximaCola,
		&i.VentanaReclamoMs,
		&i.ModoDegradado,
		&i.CursorBase,
		&i.RelojDesde,
		&i.VersionConfig,
		&i.CreadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.AbiertaEn,
		&i.CerradaEn,
	)
	return i, err
}
