// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

// Catálogo cerrado de acciones auditables (ADR 0005). Fuente de verdad de docs/catalogos/acciones-auditoria.md.
type AuditoriaAccione struct {
	// Verbo canónico recurso.accion en snake_case; inmutable una vez publicado.
	Accion   string `json:"accion"`
	Contexto string `json:"contexto"`
	// Recurso por defecto que afecta la acción; se replica en auditoria.recurso para poder consultar sin JOIN.
	Recurso     string             `json:"recurso"`
	Descripcion string             `json:"descripcion"`
	CreadaEn    pgtype.Timestamptz `json:"creada_en"`
}

// Sellos firmados del último hash de la cadena (prueba de existencia en el tiempo). referencia_externa guarda el token RFC 3161 o la URL del objeto WORM cuando exista.
type AuditoriaAncla struct {
	ID                 pgtype.UUID        `json:"id"`
	CreadaEn           pgtype.Timestamptz `json:"creada_en"`
	SecuenciaHasta     int64              `json:"secuencia_hasta"`
	HashAnclado        string             `json:"hash_anclado"`
	AlgoritmoFirma     string             `json:"algoritmo_firma"`
	Firma              string             `json:"firma"`
	IdentificadorClave string             `json:"identificador_clave"`
	ReferenciaExterna  pgtype.Text        `json:"referencia_externa"`
}

// Historial append-only de corridas del verificador de cadena. El último registro `integra` es el checkpoint de arranque del job.
type AuditoriaVerificacione struct {
	ID                   pgtype.UUID        `json:"id"`
	EjecutadaEn          pgtype.Timestamptz `json:"ejecutada_en"`
	SecuenciaDesde       int64              `json:"secuencia_desde"`
	SecuenciaHasta       int64              `json:"secuencia_hasta"`
	RegistrosVerificados int64              `json:"registros_verificados"`
	Resultado            string             `json:"resultado"`
	SecuenciaRota        pgtype.Int8        `json:"secuencia_rota"`
	HashUltimoVerificado pgtype.Text        `json:"hash_ultimo_verificado"`
	Detalle              pgtype.Text        `json:"detalle"`
	Ejecutor             string             `json:"ejecutor"`
}

// Bitácora forense append-only con hash-chaining SHA-256 (ADR 0005). Sólo INSERT y SELECT: UPDATE/DELETE/TRUNCATE bloqueados por permisos y por trigger.
type Auditorium struct {
	ID pgtype.UUID `json:"id"`
	// Versión del algoritmo de serialización canónica; forma parte del payload hasheado.
	VersionHash int16 `json:"version_hash"`
	// Consecutiva estricta sin huecos, asignada por trigger bajo advisory lock. Un hueco = fila borrada.
	Secuencia int64 `json:"secuencia"`
	// clock_timestamp() del INSERT, forzado por trigger. Precisión de microsegundos.
	MarcaTiempo pgtype.Timestamptz `json:"marca_tiempo"`
	// EventoDominio.OcurridoEn() según el puerto Reloj de la aplicación.
	OcurridoEn pgtype.Timestamptz `json:"ocurrido_en"`
	// Actor. NULL si no se resolvió (p. ej. login con correo inexistente, INV-ID-11).
	UsuarioID      pgtype.UUID `json:"usuario_id"`
	OrganizacionID pgtype.UUID `json:"organizacion_id"`
	// FK al catálogo cerrado auditoria_acciones (INV-ID-17).
	Accion            string      `json:"accion"`
	Recurso           string      `json:"recurso"`
	RecursoID         pgtype.Text `json:"recurso_id"`
	Resultado         string      `json:"resultado"`
	IpOrigen          *netip.Addr `json:"ip_origen"`
	HuellaDispositivo pgtype.Text `json:"huella_dispositivo"`
	// Correlaciona con las trazas distribuidas (middleware de plataforma/servidor).
	IDSolicitud pgtype.Text `json:"id_solicitud"`
	// Contexto adicional JSONB. Prohibido: contraseñas, hashes, tokens, OTPs.
	Detalles []byte `json:"detalles"`
	// hash_actual de la fila secuencia-1; 64 ceros en el registro génesis.
	HashAnterior string `json:"hash_anterior"`
	// SHA-256 hex del payload canónico. Lo calcula el trigger, nunca la aplicación.
	HashActual string `json:"hash_actual"`
}

// VO CodigoRespaldoMFA dentro del agregado FactorMFA (ADR 0040): 10 filas por factor confirmado, generadas junto con la confirmacion, nunca antes.
type CodigosRespaldoMfa struct {
	ID       pgtype.UUID `json:"id"`
	FactorID pgtype.UUID `json:"factor_id"`
	// SHA-256 hex del codigo de respaldo. El valor en claro NUNCA se persiste (solo se muestra una vez, en la respuesta de ConfirmarFactorMFA).
	HashCodigo string             `json:"hash_codigo"`
	UsadoEn    pgtype.Timestamptz `json:"usado_en"`
}

// Agregado FactorMFA (contexto Identidad, docs/design/otp-mfa.md). id generado por la aplicacion.
type FactoresMfa struct {
	ID        pgtype.UUID `json:"id"`
	UsuarioID pgtype.UUID `json:"usuario_id"`
	Tipo      string      `json:"tipo"`
	// Secreto TOTP CIFRADO (AES-256-GCM, CifradorSecretos) — reversible, nunca un hash (INV-MFA-02). El secreto en claro nunca se persiste.
	SecretoCifrado []byte `json:"secreto_cifrado"`
	// Hecho historico: true desde la primera verificacion exitosa, nunca vuelve a false. No confundir con activo.
	Confirmado bool `json:"confirmado"`
	// Estado vigente: true al habilitar, false tras Deshabilitar. "Confirmado" a efectos de INV-MFA-01/limite del MVP significa confirmado=true AND activo=true (ver puertos/salida.go).
	Activo       bool               `json:"activo"`
	CreadoEn     pgtype.Timestamptz `json:"creado_en"`
	ConfirmadoEn pgtype.Timestamptz `json:"confirmado_en"`
}

// Agregado Invitacion (contexto Tenencia). Nunca se borra fisicamente: transiciona a un estado terminal (aceptada/revocada/expirada) que se conserva como evidencia de auditoria.
type Invitacione struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizacionID     pgtype.UUID        `json:"organizacion_id"`
	CorreoDestinatario string             `json:"correo_destinatario"`
	RolPropuesto       string             `json:"rol_propuesto"`
	Estado             string             `json:"estado"`
	HashToken          string             `json:"hash_token"`
	InvitadaPor        pgtype.UUID        `json:"invitada_por"`
	CreadaEn           pgtype.Timestamptz `json:"creada_en"`
	ExpiraEn           pgtype.Timestamptz `json:"expira_en"`
	ResueltaEn         pgtype.Timestamptz `json:"resuelta_en"`
}

// Agregado Membresia (contexto Tenencia). Nunca se borra fisicamente (INV-TEN-08): transiciona a estado removida.
type Membresia struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizacionID pgtype.UUID        `json:"organizacion_id"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	Rol            string             `json:"rol"`
	Estado         string             `json:"estado"`
	OtorgadaPor    pgtype.UUID        `json:"otorgada_por"`
	CreadaEn       pgtype.Timestamptz `json:"creada_en"`
	ActualizadaEn  pgtype.Timestamptz `json:"actualizada_en"`
	RemovidaEn     pgtype.Timestamptz `json:"removida_en"`
}

// Agregado Organizacion (contexto Tenencia). id es UUIDv7 generado por la aplicacion.
type Organizacione struct {
	ID            pgtype.UUID        `json:"id"`
	Alias         string             `json:"alias"`
	Nombre        string             `json:"nombre"`
	Estado        string             `json:"estado"`
	CreadaPor     pgtype.UUID        `json:"creada_por"`
	CreadaEn      pgtype.Timestamptz `json:"creada_en"`
	ActualizadaEn pgtype.Timestamptz `json:"actualizada_en"`
	ArchivadaEn   pgtype.Timestamptz `json:"archivada_en"`
	MotivoEstado  pgtype.Text        `json:"motivo_estado"`
}

// Configuracion operativa de las colas de acceso virtual (contexto Confianza). El estado efimero de la cola vive en Redis; esta tabla es la fuente de verdad duradera y auditable (INV-COLA-12).
type SalasEspera struct {
	ID                    pgtype.UUID        `json:"id"`
	Alias                 string             `json:"alias"`
	AlcanceTipo           string             `json:"alcance_tipo"`
	AlcanceOrganizacionID pgtype.UUID        `json:"alcance_organizacion_id"`
	RutaProtegida         string             `json:"ruta_protegida"`
	Estado                string             `json:"estado"`
	RitmoAdmision         int32              `json:"ritmo_admision"`
	CapacidadMaximaCola   int64              `json:"capacidad_maxima_cola"`
	VentanaReclamoMs      int32              `json:"ventana_reclamo_ms"`
	ModoDegradado         string             `json:"modo_degradado"`
	CursorBase            int64              `json:"cursor_base"`
	RelojDesde            pgtype.Timestamptz `json:"reloj_desde"`
	VersionConfig         int64              `json:"version_config"`
	CreadaPor             pgtype.UUID        `json:"creada_por"`
	CreadaEn              pgtype.Timestamptz `json:"creada_en"`
	ActualizadaEn         pgtype.Timestamptz `json:"actualizada_en"`
	AbiertaEn             pgtype.Timestamptz `json:"abierta_en"`
	CerradaEn             pgtype.Timestamptz `json:"cerrada_en"`
}

type Sesione struct {
	ID                  pgtype.UUID        `json:"id"`
	UsuarioID           pgtype.UUID        `json:"usuario_id"`
	Estado              string             `json:"estado"`
	Generacion          int32              `json:"generacion"`
	CreadaEn            pgtype.Timestamptz `json:"creada_en"`
	ActualizadaEn       pgtype.Timestamptz `json:"actualizada_en"`
	UltimaRenovacionEn  pgtype.Timestamptz `json:"ultima_renovacion_en"`
	ExpiraInactividadEn pgtype.Timestamptz `json:"expira_inactividad_en"`
	ExpiraAbsolutoEn    pgtype.Timestamptz `json:"expira_absoluto_en"`
	RevocadaEn          pgtype.Timestamptz `json:"revocada_en"`
	MotivoRevocacion    pgtype.Text        `json:"motivo_revocacion"`
	IpOrigen            *netip.Addr        `json:"ip_origen"`
	AgenteUsuario       pgtype.Text        `json:"agente_usuario"`
	HuellaDispositivo   pgtype.Text        `json:"huella_dispositivo"`
}

type TokensRefresco struct {
	HashToken   string             `json:"hash_token"`
	SesionID    pgtype.UUID        `json:"sesion_id"`
	Generacion  int32              `json:"generacion"`
	EmitidoEn   pgtype.Timestamptz `json:"emitido_en"`
	ExpiraEn    pgtype.Timestamptz `json:"expira_en"`
	ConsumidoEn pgtype.Timestamptz `json:"consumido_en"`
	HashSucesor pgtype.Text        `json:"hash_sucesor"`
}

// Tokens de un solo uso para verificación de correo (sección 3.4 del diseño). Solo se persiste el hash SHA-256 del token, nunca el valor plano (INV-ID-21). Vigencia 24h, constante en aplicacion/tokens_verificacion.go.
type TokensVerificacionCorreo struct {
	// Hash SHA-256 (hex) del token en claro. Nunca se persiste el token plano.
	HashToken string `json:"hash_token"`
	// UNIQUE: un usuario tiene como máximo un token activo. Guardar es upsert por esta columna (ON CONFLICT DO UPDATE), no dos pasos separados.
	UsuarioID pgtype.UUID `json:"usuario_id"`
	// Vigencia de 24 horas desde la emisión (sección 3.4 del diseño).
	ExpiraEn pgtype.Timestamptz `json:"expira_en"`
	CreadoEn pgtype.Timestamptz `json:"creado_en"`
}

// Agregado Usuario del contexto Identidad. Único producto (ADR 0002): tabla global, sin organizacion_id.
type Usuario struct {
	ID pgtype.UUID `json:"id"`
	// Correo normalizado (minúsculas, NFC) por el VO Correo antes de persistir.
	Correo string `json:"correo"`
	// Hash en formato PHC (Argon2id, ver ADR 0008). Nunca se registra en logs.
	ContrasenaHash string `json:"contrasena_hash"`
	// EstadoUsuario: pendiente_verificacion | activo | suspendido | bloqueado | anonimizado.
	Estado        string             `json:"estado"`
	TieneMfa      bool               `json:"tiene_mfa"`
	CreadoEn      pgtype.Timestamptz `json:"creado_en"`
	ActualizadoEn pgtype.Timestamptz `json:"actualizado_en"`
	// Nulo hasta el primer login exitoso.
	UltimoAccesoEn pgtype.Timestamptz `json:"ultimo_acceso_en"`
}
