// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Queries sqlc del contexto Confianza. Implementan
	// confianza/puertos.RepositorioSalasDeEspera (ver
	// docs/design/colas-virtuales.md, sección 2.2/6.1, y la migración
	// 000017_crear_salas_espera).
	//
	// Regla de frontera (INV-COLA, mismo criterio que INV-ID-20/INV-ACC-20/
	// INV-TEN-29): solo el adaptador confianza/adaptadores/postgres consume
	// este código generado. `creada_por` y `alcance_organizacion_id` son
	// integridad referencial hacia usuarios/organizaciones, no permiso de
	// lectura de esas tablas: ninguna consulta de este archivo hace JOIN contra
	// `usuarios` ni `organizaciones`.
	//
	// No hay RLS sobre `salas_espera` (§6.1 del diseño: Confianza no es
	// multi-tenant sobre esta tabla), así que estas queries no dependen de
	// ningún `SET LOCAL app.*` previo, a diferencia de las de Tenencia.
	// Upsert del agregado completo: los campos de identidad (alias, alcance,
	// ruta, creada_por, creada_en) se fijan solo en el INSERT inicial porque
	// ninguna mutación de negocio de SalaDeEspera los cambia después de
	// creada la fila (dominio/sala_espera.go no expone ningún método que los
	// toque); los campos operativos (estado, ritmo, capacidad, ventana,
	// modo_degradado, cursor_base, reloj_desde, abierta_en, cerrada_en) se
	// reescriben en cada Guardar. version_config se incrementa en cada UPDATE
	// como bitácora de cuántas veces cambió la configuración operativa; el
	// agregado de dominio no la lee ni la expone (no es una invariante de
	// negocio, solo trazabilidad de la fila).
	GuardarSalaDeEspera(ctx context.Context, arg GuardarSalaDeEsperaParams) error
	// Consulta del reconciliador (§3.7 del diseño), una cada 15s por réplica:
	// se apoya en el índice parcial salas_espera_vigentes_idx.
	ListarSalasDeEsperaVigentes(ctx context.Context) ([]SalasEspera, error)
	ObtenerSalaDeEsperaPorAlias(ctx context.Context, alias string) (SalasEspera, error)
	ObtenerSalaDeEsperaPorID(ctx context.Context, id pgtype.UUID) (SalasEspera, error)
}

var _ Querier = (*Queries)(nil)
