// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ActualizarInvitacion(ctx context.Context, arg ActualizarInvitacionParams) (Invitacione, error)
	ActualizarMembresia(ctx context.Context, arg ActualizarMembresiaParams) (Membresia, error)
	// Persiste el estado completo del agregado tras una mutación de negocio
	// (Renombrar, CambiarAlias, Suspender, Reactivar, Archivar). Mismo patrón
	// que ActualizarSesion en acceso/db/consultas: el adaptador intenta este
	// UPDATE primero; si no afecta ninguna fila (pgx.ErrNoRows con :one +
	// RETURNING) es porque la organización todavía no existe, y entonces se
	// hace el INSERT (CrearOrganizacion).
	ActualizarOrganizacion(ctx context.Context, arg ActualizarOrganizacionParams) (Organizacione, error)
	ContarActivasDeOrganizacion(ctx context.Context, organizacionID pgtype.UUID) (int64, error)
	ContarInvitacionesPendientesDeOrganizacion(ctx context.Context, organizacionID pgtype.UUID) (int64, error)
	ContarOrganizacionesPropiasDeUsuario(ctx context.Context, usuarioID pgtype.UUID) (int64, error)
	ContarPropietariosActivos(ctx context.Context, organizacionID pgtype.UUID) (int64, error)
	// --- Invitaciones ---------------------------------------------------------------
	CrearInvitacion(ctx context.Context, arg CrearInvitacionParams) (Invitacione, error)
	// --- Membresías ---------------------------------------------------------------
	CrearMembresia(ctx context.Context, arg CrearMembresiaParams) (Membresia, error)
	// Queries sqlc del contexto Tenencia. Implementan
	// tenencia/puertos.RepositorioOrganizaciones, RepositorioMembresias y
	// RepositorioInvitaciones (ver docs/design/tenencia-bounded-context.md,
	// sección 2.2, y las migraciones 000009_crear_organizaciones_membresias,
	// 000013_crear_invitaciones y 000014_rls_tenencia).
	//
	// Regla de frontera (INV-TEN-29, mismo criterio que INV-ID-20/INV-ACC-20):
	// solo el adaptador tenencia/adaptadores/postgres consume este código
	// generado. Ninguna consulta de este archivo incluye la tabla `usuarios`
	// en su FROM o su JOIN: las columnas *_id que referencian usuarios(id) son
	// integridad referencial, no permiso de lectura de esa tabla.
	//
	// ObtenerInvitacionPorHash usa la función SECURITY DEFINER
	// tenencia_resolver_invitacion (000014), la ÚNICA vía de escape de RLS del
	// contexto: quien acepta una invitación todavía no es miembro de ninguna
	// organización, así que no hay `app.organizacion_actual` posible en ese
	// punto.
	// --- Organizaciones -----------------------------------------------------------
	CrearOrganizacion(ctx context.Context, arg CrearOrganizacionParams) (Organizacione, error)
	ListarInvitacionesPendientesDeOrganizacion(ctx context.Context, organizacionID pgtype.UUID) ([]Invitacione, error)
	ListarMembresiasDeOrganizacion(ctx context.Context, organizacionID pgtype.UUID) ([]Membresia, error)
	ListarMembresiasDeUsuario(ctx context.Context, usuarioID pgtype.UUID) ([]Membresia, error)
	ObtenerInvitacionPendiente(ctx context.Context, arg ObtenerInvitacionPendienteParams) (Invitacione, error)
	// Única vía de escape de RLS del contexto (§6.3 del diseño, ADR candidato
	// 0031): función SECURITY DEFINER, no una consulta directa a la tabla. Los
	// casts explícitos son necesarios para que sqlc infiera el tipo Go de cada
	// columna: sin ellos, una función que devuelve TABLE(...) queda tipada
	// como `interface{}` columna por columna.
	ObtenerInvitacionPorHash(ctx context.Context, pHash string) (ObtenerInvitacionPorHashRow, error)
	ObtenerInvitacionPorID(ctx context.Context, id pgtype.UUID) (Invitacione, error)
	ObtenerMembresiaPorID(ctx context.Context, id pgtype.UUID) (Membresia, error)
	// Camino caliente de autorización (§3.7 del diseño): se sirve del índice
	// único parcial membresias_vigente_idx (INV-TEN-09).
	ObtenerMembresiaVigente(ctx context.Context, arg ObtenerMembresiaVigenteParams) (Membresia, error)
	// RepositorioOrganizaciones.CargarParaActualizar (§1.2, INV-TEN-06): toma
	// el candado de la fila raíz. Solo tiene sentido dentro de una
	// UnidadDeTrabajo (transacción ya abierta).
	ObtenerOrganizacionParaActualizar(ctx context.Context, id pgtype.UUID) (Organizacione, error)
	ObtenerOrganizacionPorAlias(ctx context.Context, alias string) (Organizacione, error)
	ObtenerOrganizacionPorID(ctx context.Context, id pgtype.UUID) (Organizacione, error)
}

var _ Querier = (*Queries)(nil)
