// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenencia.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const actualizarInvitacion = `-- name: ActualizarInvitacion :one
UPDATE invitaciones
SET estado = $2,
    resuelta_en = $3
WHERE id = $1
RETURNING id, organizacion_id, correo_destinatario, rol_propuesto, estado, hash_token, invitada_por, creada_en, expira_en, resuelta_en
`

type ActualizarInvitacionParams struct {
	ID         pgtype.UUID        `json:"id"`
	Estado     string             `json:"estado"`
	ResueltaEn pgtype.Timestamptz `json:"resuelta_en"`
}

func (q *Queries) ActualizarInvitacion(ctx context.Context, arg ActualizarInvitacionParams) (Invitacione, error) {
	row := q.db.QueryRow(ctx, actualizarInvitacion, arg.ID, arg.Estado, arg.ResueltaEn)
	var i Invitacione
	err := row.Scan(
		&i.ID,
		&i.OrganizacionID,
		&i.CorreoDestinatario,
		&i.RolPropuesto,
		&i.Estado,
		&i.HashToken,
		&i.InvitadaPor,
		&i.CreadaEn,
		&i.ExpiraEn,
		&i.ResueltaEn,
	)
	return i, err
}

const actualizarMembresia = `-- name: ActualizarMembresia :one
UPDATE membresias
SET rol = $2,
    estado = $3,
    actualizada_en = $4,
    removida_en = $5
WHERE id = $1
RETURNING id, organizacion_id, usuario_id, rol, estado, otorgada_por, creada_en, actualizada_en, removida_en
`

type ActualizarMembresiaParams struct {
	ID            pgtype.UUID        `json:"id"`
	Rol           string             `json:"rol"`
	Estado        string             `json:"estado"`
	ActualizadaEn pgtype.Timestamptz `json:"actualizada_en"`
	RemovidaEn    pgtype.Timestamptz `json:"removida_en"`
}

func (q *Queries) ActualizarMembresia(ctx context.Context, arg ActualizarMembresiaParams) (Membresia, error) {
	row := q.db.QueryRow(ctx, actualizarMembresia,
		arg.ID,
		arg.Rol,
		arg.Estado,
		arg.ActualizadaEn,
		arg.RemovidaEn,
	)
	var i Membresia
	err := row.Scan(
		&i.ID,
		&i.OrganizacionID,
		&i.UsuarioID,
		&i.Rol,
		&i.Estado,
		&i.OtorgadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.RemovidaEn,
	)
	return i, err
}

const actualizarOrganizacion = `-- name: ActualizarOrganizacion :one
UPDATE organizaciones
SET alias = $2,
    nombre = $3,
    estado = $4,
    actualizada_en = $5,
    archivada_en = $6,
    motivo_estado = $7
WHERE id = $1
RETURNING id, alias, nombre, estado, creada_por, creada_en, actualizada_en, archivada_en, motivo_estado
`

type ActualizarOrganizacionParams struct {
	ID            pgtype.UUID        `json:"id"`
	Alias         string             `json:"alias"`
	Nombre        string             `json:"nombre"`
	Estado        string             `json:"estado"`
	ActualizadaEn pgtype.Timestamptz `json:"actualizada_en"`
	ArchivadaEn   pgtype.Timestamptz `json:"archivada_en"`
	MotivoEstado  pgtype.Text        `json:"motivo_estado"`
}

// Persiste el estado completo del agregado tras una mutación de negocio
// (Renombrar, CambiarAlias, Suspender, Reactivar, Archivar). Mismo patrón
// que ActualizarSesion en acceso/db/consultas: el adaptador intenta este
// UPDATE primero; si no afecta ninguna fila (pgx.ErrNoRows con :one +
// RETURNING) es porque la organización todavía no existe, y entonces se
// hace el INSERT (CrearOrganizacion).
func (q *Queries) ActualizarOrganizacion(ctx context.Context, arg ActualizarOrganizacionParams) (Organizacione, error) {
	row := q.db.QueryRow(ctx, actualizarOrganizacion,
		arg.ID,
		arg.Alias,
		arg.Nombre,
		arg.Estado,
		arg.ActualizadaEn,
		arg.ArchivadaEn,
		arg.MotivoEstado,
	)
	var i Organizacione
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Nombre,
		&i.Estado,
		&i.CreadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.ArchivadaEn,
		&i.MotivoEstado,
	)
	return i, err
}

const contarActivasDeOrganizacion = `-- name: ContarActivasDeOrganizacion :one
SELECT COUNT(*) FROM membresias WHERE organizacion_id = $1 AND estado = 'activa'
`

func (q *Queries) ContarActivasDeOrganizacion(ctx context.Context, organizacionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarActivasDeOrganizacion, organizacionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarInvitacionesPendientesDeOrganizacion = `-- name: ContarInvitacionesPendientesDeOrganizacion :one
SELECT COUNT(*) FROM invitaciones WHERE organizacion_id = $1 AND estado = 'pendiente'
`

func (q *Queries) ContarInvitacionesPendientesDeOrganizacion(ctx context.Context, organizacionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarInvitacionesPendientesDeOrganizacion, organizacionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarOrganizacionesPropiasDeUsuario = `-- name: ContarOrganizacionesPropiasDeUsuario :one
SELECT COUNT(*) FROM membresias WHERE usuario_id = $1 AND rol = 'propietario' AND estado = 'activa'
`

func (q *Queries) ContarOrganizacionesPropiasDeUsuario(ctx context.Context, usuarioID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarOrganizacionesPropiasDeUsuario, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarPropietariosActivos = `-- name: ContarPropietariosActivos :one
SELECT COUNT(*) FROM membresias WHERE organizacion_id = $1 AND rol = 'propietario' AND estado = 'activa'
`

func (q *Queries) ContarPropietariosActivos(ctx context.Context, organizacionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarPropietariosActivos, organizacionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearInvitacion = `-- name: CrearInvitacion :one

INSERT INTO invitaciones (
    id, organizacion_id, correo_destinatario, rol_propuesto, estado,
    hash_token, invitada_por, creada_en, expira_en, resuelta_en
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, organizacion_id, correo_destinatario, rol_propuesto, estado, hash_token, invitada_por, creada_en, expira_en, resuelta_en
`

type CrearInvitacionParams struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizacionID     pgtype.UUID        `json:"organizacion_id"`
	CorreoDestinatario string             `json:"correo_destinatario"`
	RolPropuesto       string             `json:"rol_propuesto"`
	Estado             string             `json:"estado"`
	HashToken          string             `json:"hash_token"`
	InvitadaPor        pgtype.UUID        `json:"invitada_por"`
	CreadaEn           pgtype.Timestamptz `json:"creada_en"`
	ExpiraEn           pgtype.Timestamptz `json:"expira_en"`
	ResueltaEn         pgtype.Timestamptz `json:"resuelta_en"`
}

// --- Invitaciones ---------------------------------------------------------------
func (q *Queries) CrearInvitacion(ctx context.Context, arg CrearInvitacionParams) (Invitacione, error) {
	row := q.db.QueryRow(ctx, crearInvitacion,
		arg.ID,
		arg.OrganizacionID,
		arg.CorreoDestinatario,
		arg.RolPropuesto,
		arg.Estado,
		arg.HashToken,
		arg.InvitadaPor,
		arg.CreadaEn,
		arg.ExpiraEn,
		arg.ResueltaEn,
	)
	var i Invitacione
	err := row.Scan(
		&i.ID,
		&i.OrganizacionID,
		&i.CorreoDestinatario,
		&i.RolPropuesto,
		&i.Estado,
		&i.HashToken,
		&i.InvitadaPor,
		&i.CreadaEn,
		&i.ExpiraEn,
		&i.ResueltaEn,
	)
	return i, err
}

const crearMembresia = `-- name: CrearMembresia :one

INSERT INTO membresias (
    id, organizacion_id, usuario_id, rol, estado, otorgada_por,
    creada_en, actualizada_en, removida_en
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $7, $8
)
RETURNING id, organizacion_id, usuario_id, rol, estado, otorgada_por, creada_en, actualizada_en, removida_en
`

type CrearMembresiaParams struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizacionID pgtype.UUID        `json:"organizacion_id"`
	UsuarioID      pgtype.UUID        `json:"usuario_id"`
	Rol            string             `json:"rol"`
	Estado         string             `json:"estado"`
	OtorgadaPor    pgtype.UUID        `json:"otorgada_por"`
	CreadaEn       pgtype.Timestamptz `json:"creada_en"`
	RemovidaEn     pgtype.Timestamptz `json:"removida_en"`
}

// --- Membresías ---------------------------------------------------------------
func (q *Queries) CrearMembresia(ctx context.Context, arg CrearMembresiaParams) (Membresia, error) {
	row := q.db.QueryRow(ctx, crearMembresia,
		arg.ID,
		arg.OrganizacionID,
		arg.UsuarioID,
		arg.Rol,
		arg.Estado,
		arg.OtorgadaPor,
		arg.CreadaEn,
		arg.RemovidaEn,
	)
	var i Membresia
	err := row.Scan(
		&i.ID,
		&i.OrganizacionID,
		&i.UsuarioID,
		&i.Rol,
		&i.Estado,
		&i.OtorgadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.RemovidaEn,
	)
	return i, err
}

const crearOrganizacion = `-- name: CrearOrganizacion :one


INSERT INTO organizaciones (
    id, alias, nombre, estado, creada_por, creada_en, actualizada_en,
    archivada_en, motivo_estado
) VALUES (
    $1, $2, $3, $4, $5, $6, $6, $7, $8
)
RETURNING id, alias, nombre, estado, creada_por, creada_en, actualizada_en, archivada_en, motivo_estado
`

type CrearOrganizacionParams struct {
	ID           pgtype.UUID        `json:"id"`
	Alias        string             `json:"alias"`
	Nombre       string             `json:"nombre"`
	Estado       string             `json:"estado"`
	CreadaPor    pgtype.UUID        `json:"creada_por"`
	CreadaEn     pgtype.Timestamptz `json:"creada_en"`
	ArchivadaEn  pgtype.Timestamptz `json:"archivada_en"`
	MotivoEstado pgtype.Text        `json:"motivo_estado"`
}

// Queries sqlc del contexto Tenencia. Implementan
// tenencia/puertos.RepositorioOrganizaciones, RepositorioMembresias y
// RepositorioInvitaciones (ver docs/design/tenencia-bounded-context.md,
// sección 2.2, y las migraciones 000009_crear_organizaciones_membresias,
// 000013_crear_invitaciones y 000014_rls_tenencia).
//
// Regla de frontera (INV-TEN-29, mismo criterio que INV-ID-20/INV-ACC-20):
// solo el adaptador tenencia/adaptadores/postgres consume este código
// generado. Ninguna consulta de este archivo incluye la tabla `usuarios`
// en su FROM o su JOIN: las columnas *_id que referencian usuarios(id) son
// integridad referencial, no permiso de lectura de esa tabla.
//
// ObtenerInvitacionPorHash usa la función SECURITY DEFINER
// tenencia_resolver_invitacion (000014), la ÚNICA vía de escape de RLS del
// contexto: quien acepta una invitación todavía no es miembro de ninguna
// organización, así que no hay `app.organizacion_actual` posible en ese
// punto.
// --- Organizaciones -----------------------------------------------------------
func (q *Queries) CrearOrganizacion(ctx context.Context, arg CrearOrganizacionParams) (Organizacione, error) {
	row := q.db.QueryRow(ctx, crearOrganizacion,
		arg.ID,
		arg.Alias,
		arg.Nombre,
		arg.Estado,
		arg.CreadaPor,
		arg.CreadaEn,
		arg.ArchivadaEn,
		arg.MotivoEstado,
	)
	var i Organizacione
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Nombre,
		&i.Estado,
		&i.CreadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.ArchivadaEn,
		&i.MotivoEstado,
	)
	return i, err
}

const listarInvitacionesPendientesDeOrganizacion = `-- name: ListarInvitacionesPendientesDeOrganizacion :many
SELECT id, organizacion_id, correo_destinatario, rol_propuesto, estado, hash_token, invitada_por, creada_en, expira_en, resuelta_en FROM invitaciones WHERE organizacion_id = $1 AND estado = 'pendiente' ORDER BY creada_en DESC
`

func (q *Queries) ListarInvitacionesPendientesDeOrganizacion(ctx context.Context, organizacionID pgtype.UUID) ([]Invitacione, error) {
	rows, err := q.db.Query(ctx, listarInvitacionesPendientesDeOrganizacion, organizacionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitacione
	for rows.Next() {
		var i Invitacione
		if err := rows.Scan(
			&i.ID,
			&i.OrganizacionID,
			&i.CorreoDestinatario,
			&i.RolPropuesto,
			&i.Estado,
			&i.HashToken,
			&i.InvitadaPor,
			&i.CreadaEn,
			&i.ExpiraEn,
			&i.ResueltaEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMembresiasDeOrganizacion = `-- name: ListarMembresiasDeOrganizacion :many
SELECT id, organizacion_id, usuario_id, rol, estado, otorgada_por, creada_en, actualizada_en, removida_en FROM membresias WHERE organizacion_id = $1 ORDER BY creada_en ASC
`

func (q *Queries) ListarMembresiasDeOrganizacion(ctx context.Context, organizacionID pgtype.UUID) ([]Membresia, error) {
	rows, err := q.db.Query(ctx, listarMembresiasDeOrganizacion, organizacionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membresia
	for rows.Next() {
		var i Membresia
		if err := rows.Scan(
			&i.ID,
			&i.OrganizacionID,
			&i.UsuarioID,
			&i.Rol,
			&i.Estado,
			&i.OtorgadaPor,
			&i.CreadaEn,
			&i.ActualizadaEn,
			&i.RemovidaEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarMembresiasDeUsuario = `-- name: ListarMembresiasDeUsuario :many
SELECT id, organizacion_id, usuario_id, rol, estado, otorgada_por, creada_en, actualizada_en, removida_en FROM membresias WHERE usuario_id = $1 AND estado <> 'removida' ORDER BY creada_en ASC
`

func (q *Queries) ListarMembresiasDeUsuario(ctx context.Context, usuarioID pgtype.UUID) ([]Membresia, error) {
	rows, err := q.db.Query(ctx, listarMembresiasDeUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Membresia
	for rows.Next() {
		var i Membresia
		if err := rows.Scan(
			&i.ID,
			&i.OrganizacionID,
			&i.UsuarioID,
			&i.Rol,
			&i.Estado,
			&i.OtorgadaPor,
			&i.CreadaEn,
			&i.ActualizadaEn,
			&i.RemovidaEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerInvitacionPendiente = `-- name: ObtenerInvitacionPendiente :one
SELECT id, organizacion_id, correo_destinatario, rol_propuesto, estado, hash_token, invitada_por, creada_en, expira_en, resuelta_en FROM invitaciones WHERE organizacion_id = $1 AND correo_destinatario = $2 AND estado = 'pendiente'
`

type ObtenerInvitacionPendienteParams struct {
	OrganizacionID     pgtype.UUID `json:"organizacion_id"`
	CorreoDestinatario string      `json:"correo_destinatario"`
}

func (q *Queries) ObtenerInvitacionPendiente(ctx context.Context, arg ObtenerInvitacionPendienteParams) (Invitacione, error) {
	row := q.db.QueryRow(ctx, obtenerInvitacionPendiente, arg.OrganizacionID, arg.CorreoDestinatario)
	var i Invitacione
	err := row.Scan(
		&i.ID,
		&i.OrganizacionID,
		&i.CorreoDestinatario,
		&i.RolPropuesto,
		&i.Estado,
		&i.HashToken,
		&i.InvitadaPor,
		&i.CreadaEn,
		&i.ExpiraEn,
		&i.ResueltaEn,
	)
	return i, err
}

const obtenerInvitacionPorHash = `-- name: ObtenerInvitacionPorHash :one
SELECT id::uuid AS id,
       organizacion_id::uuid AS organizacion_id,
       correo_destinatario::text AS correo_destinatario,
       rol_propuesto::text AS rol_propuesto,
       estado::text AS estado,
       hash_token::text AS hash_token,
       invitada_por::uuid AS invitada_por,
       creada_en::timestamptz AS creada_en,
       expira_en::timestamptz AS expira_en,
       resuelta_en::timestamptz AS resuelta_en
FROM tenencia_resolver_invitacion($1)
    AS t(id, organizacion_id, correo_destinatario, rol_propuesto, estado,
         hash_token, invitada_por, creada_en, expira_en, resuelta_en)
`

type ObtenerInvitacionPorHashRow struct {
	ID                 pgtype.UUID        `json:"id"`
	OrganizacionID     pgtype.UUID        `json:"organizacion_id"`
	CorreoDestinatario string             `json:"correo_destinatario"`
	RolPropuesto       string             `json:"rol_propuesto"`
	Estado             string             `json:"estado"`
	HashToken          string             `json:"hash_token"`
	InvitadaPor        pgtype.UUID        `json:"invitada_por"`
	CreadaEn           pgtype.Timestamptz `json:"creada_en"`
	ExpiraEn           pgtype.Timestamptz `json:"expira_en"`
	ResueltaEn         pgtype.Timestamptz `json:"resuelta_en"`
}

// Única vía de escape de RLS del contexto (§6.3 del diseño, ADR candidato
// 0031): función SECURITY DEFINER, no una consulta directa a la tabla. Los
// casts explícitos son necesarios para que sqlc infiera el tipo Go de cada
// columna: sin ellos, una función que devuelve TABLE(...) queda tipada
// como `interface{}` columna por columna.
func (q *Queries) ObtenerInvitacionPorHash(ctx context.Context, pHash string) (ObtenerInvitacionPorHashRow, error) {
	row := q.db.QueryRow(ctx, obtenerInvitacionPorHash, pHash)
	var i ObtenerInvitacionPorHashRow
	err := row.Scan(
		&i.ID,
		&i.OrganizacionID,
		&i.CorreoDestinatario,
		&i.RolPropuesto,
		&i.Estado,
		&i.HashToken,
		&i.InvitadaPor,
		&i.CreadaEn,
		&i.ExpiraEn,
		&i.ResueltaEn,
	)
	return i, err
}

const obtenerInvitacionPorID = `-- name: ObtenerInvitacionPorID :one
SELECT id, organizacion_id, correo_destinatario, rol_propuesto, estado, hash_token, invitada_por, creada_en, expira_en, resuelta_en FROM invitaciones WHERE id = $1
`

func (q *Queries) ObtenerInvitacionPorID(ctx context.Context, id pgtype.UUID) (Invitacione, error) {
	row := q.db.QueryRow(ctx, obtenerInvitacionPorID, id)
	var i Invitacione
	err := row.Scan(
		&i.ID,
		&i.OrganizacionID,
		&i.CorreoDestinatario,
		&i.RolPropuesto,
		&i.Estado,
		&i.HashToken,
		&i.InvitadaPor,
		&i.CreadaEn,
		&i.ExpiraEn,
		&i.ResueltaEn,
	)
	return i, err
}

const obtenerMembresiaPorID = `-- name: ObtenerMembresiaPorID :one
SELECT id, organizacion_id, usuario_id, rol, estado, otorgada_por, creada_en, actualizada_en, removida_en FROM membresias WHERE id = $1
`

func (q *Queries) ObtenerMembresiaPorID(ctx context.Context, id pgtype.UUID) (Membresia, error) {
	row := q.db.QueryRow(ctx, obtenerMembresiaPorID, id)
	var i Membresia
	err := row.Scan(
		&i.ID,
		&i.OrganizacionID,
		&i.UsuarioID,
		&i.Rol,
		&i.Estado,
		&i.OtorgadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.RemovidaEn,
	)
	return i, err
}

const obtenerMembresiaVigente = `-- name: ObtenerMembresiaVigente :one
SELECT id, organizacion_id, usuario_id, rol, estado, otorgada_por, creada_en, actualizada_en, removida_en FROM membresias WHERE organizacion_id = $1 AND usuario_id = $2 AND estado <> 'removida'
`

type ObtenerMembresiaVigenteParams struct {
	OrganizacionID pgtype.UUID `json:"organizacion_id"`
	UsuarioID      pgtype.UUID `json:"usuario_id"`
}

// Camino caliente de autorización (§3.7 del diseño): se sirve del índice
// único parcial membresias_vigente_idx (INV-TEN-09).
func (q *Queries) ObtenerMembresiaVigente(ctx context.Context, arg ObtenerMembresiaVigenteParams) (Membresia, error) {
	row := q.db.QueryRow(ctx, obtenerMembresiaVigente, arg.OrganizacionID, arg.UsuarioID)
	var i Membresia
	err := row.Scan(
		&i.ID,
		&i.OrganizacionID,
		&i.UsuarioID,
		&i.Rol,
		&i.Estado,
		&i.OtorgadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.RemovidaEn,
	)
	return i, err
}

const obtenerOrganizacionParaActualizar = `-- name: ObtenerOrganizacionParaActualizar :one
SELECT id, alias, nombre, estado, creada_por, creada_en, actualizada_en, archivada_en, motivo_estado FROM organizaciones WHERE id = $1 FOR UPDATE
`

// RepositorioOrganizaciones.CargarParaActualizar (§1.2, INV-TEN-06): toma
// el candado de la fila raíz. Solo tiene sentido dentro de una
// UnidadDeTrabajo (transacción ya abierta).
func (q *Queries) ObtenerOrganizacionParaActualizar(ctx context.Context, id pgtype.UUID) (Organizacione, error) {
	row := q.db.QueryRow(ctx, obtenerOrganizacionParaActualizar, id)
	var i Organizacione
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Nombre,
		&i.Estado,
		&i.CreadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.ArchivadaEn,
		&i.MotivoEstado,
	)
	return i, err
}

const obtenerOrganizacionPorAlias = `-- name: ObtenerOrganizacionPorAlias :one
SELECT id, alias, nombre, estado, creada_por, creada_en, actualizada_en, archivada_en, motivo_estado FROM organizaciones WHERE alias = $1
`

func (q *Queries) ObtenerOrganizacionPorAlias(ctx context.Context, alias string) (Organizacione, error) {
	row := q.db.QueryRow(ctx, obtenerOrganizacionPorAlias, alias)
	var i Organizacione
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Nombre,
		&i.Estado,
		&i.CreadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.ArchivadaEn,
		&i.MotivoEstado,
	)
	return i, err
}

const obtenerOrganizacionPorID = `-- name: ObtenerOrganizacionPorID :one
SELECT id, alias, nombre, estado, creada_por, creada_en, actualizada_en, archivada_en, motivo_estado FROM organizaciones WHERE id = $1
`

func (q *Queries) ObtenerOrganizacionPorID(ctx context.Context, id pgtype.UUID) (Organizacione, error) {
	row := q.db.QueryRow(ctx, obtenerOrganizacionPorID, id)
	var i Organizacione
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Nombre,
		&i.Estado,
		&i.CreadaPor,
		&i.CreadaEn,
		&i.ActualizadaEn,
		&i.ArchivadaEn,
		&i.MotivoEstado,
	)
	return i, err
}
